-- MySQL Script generated by MySQL Workbench
-- dom 23 mai 2021 20:13:00
-- Model: mjaAlocacoes Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mjaAlocacoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mjaAlocacoes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS mjaAlocacoes;
CREATE SCHEMA IF NOT EXISTS mjaAlocacoes;
USE mjaAlocacoes ;

-- -----------------------------------------------------
-- Table mjaAlocacoes.Cliente
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.Cliente (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(40) NULL,
  email VARCHAR(160) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  cpf VARCHAR(20) NULL,
  fisica_juridica INT NULL,
  cnpj VARCHAR(45) NULL,
  razao_social VARCHAR(45) NULL,
  UNIQUE INDEX Id_UNIQUE (id ASC),
  PRIMARY KEY (id),
  UNIQUE INDEX CNPJ_UNIQUE (cnpj ASC),
  UNIQUE INDEX cpf_UNIQUE (cpf ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.Endereco
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.Endereco (
  id INT NOT NULL AUTO_INCREMENT,
  cliente_id INT NOT NULL,
  Numero VARCHAR(10) NOT NULL,
  Complemento VARCHAR(40) NULL,
  Cidade VARCHAR(60) NOT NULL,
  Estado CHAR(2) NOT NULL,
  Pais CHAR(2) NOT NULL,
  CEP CHAR(10) NOT NULL,
  UNIQUE INDEX idPedido_UNIQUE (id ASC),
  PRIMARY KEY (id),
  CONSTRAINT fk_Endereco_Cliente1
    FOREIGN KEY (cliente_id)
    REFERENCES mjaAlocacoes.Cliente (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.Pedido
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.Pedido (
  id INT NOT NULL AUTO_INCREMENT,
  cliente_id INT NOT NULL,
  data_abertura DATETIME NOT NULL,
  duracao_pedido TIME NOT NULL,
  total_servicos DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (id, cliente_id),
  INDEX fk_pedido_1_idx (cliente_id ASC),
  CONSTRAINT fk_pedido_1
    FOREIGN KEY (cliente_id)
    REFERENCES mjaAlocacoes.Cliente (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.TipoServico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.TipoServico (
  id INT NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(45) NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.servico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.servico (
  id INT NOT NULL AUTO_INCREMENT,
  valor_por_metro DECIMAL(10,0) NOT NULL,
  duracao_por_metro TIME NOT NULL,
  tipo_servico_id INT NOT NULL,
  PRIMARY KEY (id, tipo_servico_id),
  INDEX fk_servico_TipoServico1_idx (tipo_servico_id ASC),
  CONSTRAINT fk_servico_TipoServico1
    FOREIGN KEY (tipo_servico_id)
    REFERENCES mjaAlocacoes.TipoServico (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.Empregado
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.Empregado (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NULL,
  sobrenome VARCHAR(45) NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.ServicoPedido
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.ServicoPedido (
  id INT NOT NULL AUTO_INCREMENT,
  local INT NOT NULL,
  area_servico REAL NOT NULL,
  duracao_servico DATETIME NOT NULL,
  valor_unitario DECIMAL(10,0) NOT NULL,
  seq INT NULL,
  servico_id INT NOT NULL,
  pedido_id INT NOT NULL,
  data_realizacao DATETIME NOT NULL,
  empregado_id INT NOT NULL,
  PRIMARY KEY (id, servico_id, pedido_id, empregado_id),
  INDEX fk_ServicoPedido_servico1_idx (servico_id ASC),
  INDEX fk_ServicoPedido_Pedido1_idx (pedido_id ASC),
  INDEX fk_ServicoPedido_Empregado1_idx (empregado_id ASC),
  CONSTRAINT fk_ServicoPedido_servico1
    FOREIGN KEY (servico_id)
    REFERENCES mjaAlocacoes.servico (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ServicoPedido_Pedido1
    FOREIGN KEY (pedido_id)
    REFERENCES mjaAlocacoes.Pedido (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ServicoPedido_Empregado1
    FOREIGN KEY (empregado_id)
    REFERENCES mjaAlocacoes.Empregado (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mjaAlocacoes.ServicoHabilitado
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mjaAlocacoes.ServicoHabilitado (
  id INT NOT NULL AUTO_INCREMENT,
  empregado_id INT NOT NULL,
  tipoServico_id INT NOT NULL,
  PRIMARY KEY (id, empregado_id, tipoServico_id),
  INDEX fk_ServicoHabilitado_Empregado1_idx (empregado_id ASC),
  INDEX fk_ServicoHabilitado_TipoServico1_idx (tipoServico_id ASC),
  CONSTRAINT fk_ServicoHabilitado_Empregado1
    FOREIGN KEY (empregado_id)
    REFERENCES mjaAlocacoes.Empregado (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ServicoHabilitado_TipoServico1
    FOREIGN KEY (tipoServico_id)
    REFERENCES mjaAlocacoes.TipoServico (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
